import React,{useEffect,useMemo,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,Instagram,Menu,X,Sparkles,Smartphone,Globe2,Utensils,Target,Palette,Play,ChevronRight,ExternalLink,PlayCircle} from 'lucide-react';
import './styles.css';
import {supabase} from './supabase';
import {seedClients,seedServices,seedContents,seedProjects,seedStats} from './data';

const icons={Smartphone,Globe2,Utensils,Target,Palette,Play};
const whatsapp='https://wa.me/5511971493985?text=Ol%C3%A1%2C%20Karen!%20Conheci%20a%20Seeven%20e%20quero%20conversar%20sobre%20um%20projeto.';
const embedUrl=url=>{const m=url?.match(/instagram\.com\/(?:reel|p)\/([^/?]+)/);return m?`https://www.instagram.com/reel/${m[1]}/embed/`:url};

async function loadTable(table,fallback){
 if(!supabase)return fallback;
 const {data,error}=await supabase.from(table).select('*').eq('active',true).order('sort_order',{ascending:true});
 return error||!data?.length?fallback:data;
}

function ReelModal({item,onClose}){if(!item)return null;return <div className="media-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="media-modal-box"><button className="modal-close" onClick={onClose}><X/></button><iframe src={embedUrl(item.url)} title={item.title} loading="lazy" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"/></div></div>}

function ProjectModal({item,onClose}){if(!item)return null;return <div className="media-modal project-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="project-modal-box"><button className="modal-close" onClick={onClose}><X/></button><div className="project-modal-image">{item.cover_url?<img src={item.cover_url} alt=""/>:<div className="project-fallback">{item.title}</div>}</div><div className="project-modal-copy"><span>{item.category}</span><h3>{item.title}</h3><p>{item.description}</p><a className="button primary" href={item.url} target="_blank" rel="noreferrer">Abrir projeto no Behance <ExternalLink size={16}/></a></div></div></div>}

function App(){
 const [menu,setMenu]=useState(false),[activeService,setActiveService]=useState(0),[scroll,setScroll]=useState(0),[clients,setClients]=useState(seedClients),[services,setServices]=useState(seedServices),[contents,setContents]=useState(seedContents),[projects,setProjects]=useState(seedProjects),[filter,setFilter]=useState('TODOS'),[selected,setSelected]=useState(null),[selectedProject,setSelectedProject]=useState(null);
 useEffect(()=>{const f=()=>setScroll(scrollY);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);
 useEffect(()=>{(async()=>{setClients(await loadTable('clients',seedClients));setServices(await loadTable('services',seedServices));setContents(await loadTable('contents',seedContents));setProjects(await loadTable('projects',seedProjects));})()},[]);
 const names=useMemo(()=>['TODOS',...clients.map(c=>c.name)], [clients]);
 const visibleContents=filter==='TODOS'?contents:contents.filter(c=>c.client_name===filter);
 const activeServiceData=services[activeService]||services[0];
 return <div className="app"><div className="noise"/>
 <header className={scroll>20?'header scrolled':'header'}><a className="brand" href="#top"><span className="brand-mark">V</span><span>SEEVEN<span className="muted">/PROJECTS</span></span></a><nav className={menu?'nav open':'nav'}><a href="#showcase" onClick={()=>setMenu(false)}>Showcase</a><a href="#services" onClick={()=>setMenu(false)}>Soluções</a><a href="#portfolio" onClick={()=>setMenu(false)}>Portfólio</a><a href="#case" onClick={()=>setMenu(false)}>Case</a><a className="nav-cta" href={whatsapp}>Falar com Karen <ArrowUpRight size={15}/></a></nav><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?<X/>:<Menu/>}</button></header>
 <main id="top">
 <section className="hero"><div className="hero-grid"/><div className="hero-content"><div className="eyebrow"><span className="dot"/> DIGITAL, BUT DIFFERENT.</div><h1>Sua marca merece<br/><em>impacto.</em></h1><p className="hero-copy">Marketing, design e tecnologia para transformar negócios em experiências digitais que as pessoas lembram.</p><div className="hero-actions"><a className="button primary" href="#showcase">Explorar a Seeven <ArrowDownRight size={18}/></a><a className="text-link" href={whatsapp}>Quero falar com a Karen <ArrowUpRight size={16}/></a></div></div><div className="hero-visual"><div className="v-stage"><div className="v-glow"/><div className="v-ring ring-1"/><div className="v-ring ring-2"/><div className="v-letter">V</div><div className="float-card card-top"><span>STRATEGY</span><strong>01</strong></div><div className="float-card card-bottom"><span>DESIGN</span><strong>07</strong></div></div></div><div className="scroll-note"><span/> role para explorar</div></section>
 <section className="manifesto section"><div className="section-label">01 / MANIFESTO</div><div><h2>Não é sobre estar<br/><span>online.</span></h2><p className="big-copy">É sobre fazer alguém parar, olhar e pensar: <strong>“eu quero isso para a minha marca.”</strong></p></div></section>
 <section id="services" className="services section"><div className="section-head"><div><div className="section-label">02 / SOLUÇÕES</div><h2>O que sua marca<br/><span>poderia ser?</span></h2></div><p>Você não precisa contratar tudo.<br/>Precisa resolver o que importa.</p></div><div className="services-layout"><div className="service-list">{services.map((s,i)=>{const Icon=icons[s.icon]||Sparkles;return <button key={s.id||s.title} className={activeService===i?'service active':'service'} onMouseEnter={()=>setActiveService(i)} onClick={()=>setActiveService(i)}><span className="service-icon"><Icon size={19}/></span><span className="service-text"><small>{s.tag}</small><strong>{s.title}</strong></span><ChevronRight className="service-arrow" size={19}/></button>})}</div><div className="service-demo"><div className="demo-label">{activeServiceData?.tag}</div><div className="demo-phone"><div className="phone-notch"/><div className="phone-ui"><div className="mini-top"><span>SEEVEN</span><span>•••</span></div><div className="mini-visual"/><div className="mini-lines"><i/><i/><i/></div><div className="mini-button">{activeServiceData?.title?.toUpperCase()}</div></div></div><div className="demo-copy"><span>EXPERIÊNCIA DIGITAL</span><h3>{activeServiceData?.title}</h3><p>{activeServiceData?.description}</p></div></div></div></section>
 <section id="showcase" className="showcase section"><div className="section-label">03 / SHOWCASE</div><div className="work-title-row"><h2>O trabalho<br/><span>em movimento.</span></h2><p>Conteúdo real, projetos reais e marcas que já passaram pela Seeven.</p></div><div className="filter-row">{names.map(n=><button key={n} className={filter===n?'filter active':'filter'} onClick={()=>setFilter(n)}>{n}</button>)}</div><div className="reel-grid">{visibleContents.map((item,i)=><button className="reel-card" key={item.id||i} onClick={()=>setSelected(item)}><div className="reel-poster">{item.poster_url?<img src={item.poster_url} alt="" loading="lazy"/>:<div className="reel-generated"><span className="reel-number">{String(i+1).padStart(2,'0')}</span><strong>{item.client_name}</strong><small>{item.title}</small></div>}<div className="reel-overlay"/><div className="reel-play"><PlayCircle size={42}/></div><span className="reel-client">{item.client_name}</span></div><div className="reel-meta"><strong>{item.title}</strong><small>VER REEL <ArrowUpRight size={13}/></small></div></button>)}</div><div className="showcase-foot"><a href="https://www.instagram.com/see_7_ven/" target="_blank" rel="noreferrer">Ver Instagram da Seeven <ExternalLink size={14}/></a></div></section>
 <section id="portfolio" className="portfolio section"><div className="section-label">04 / PORTFÓLIO</div><div className="work-title-row"><h2>Projetos que<br/><span>contam a história.</span></h2><p>Direção visual, campanhas, branding, eventos e experiências.</p></div><div className="portfolio-grid">{projects.map((p,i)=><button className={'portfolio-card '+(p.featured?'featured':'')} onClick={()=>setSelectedProject(p)} key={p.id||i}><div className="portfolio-index">0{(i%9)+1}</div><div className="portfolio-art">{p.cover_url?<img src={p.cover_url} alt="" loading="lazy"/>:<div className="portfolio-art-fallback"/>}<div className="portfolio-overlay"/><div className="portfolio-copy"><span>{p.category}</span><strong>{p.title}</strong><div className="portfolio-open">VER PROJETO <ArrowUpRight size={15}/></div></div></div></button>)}</div><div className="showcase-foot"><a href="https://www.behance.net/wedeseeven" target="_blank" rel="noreferrer">Explorar Behance completo <ExternalLink size={14}/></a></div></section>
 <section id="case" className="case section"><div className="case-backdrop"/><div className="section-label">05 / CASE STUDY</div><div className="case-intro"><span className="case-kicker">SINDPETSHOP-SP</span><h2>Comunicação sindical<br/><span>não é fácil.</span></h2><p>Mesmo em um nicho complexo, estratégia e conteúdo podem transformar atenção em presença.</p></div><div className="stats">{seedStats.map((s,i)=><div className={'stat '+(i===3?'featured':'')} key={s.label}><strong>{s.value}<span>{s.suffix}</span></strong><small>{s.label}</small><em>{s.delta}</em></div>)}</div><div className="case-note"><Sparkles size={17}/><span>Dados apresentados como exemplo de desempenho. Resultados variam conforme estratégia, período e investimento.</span></div></section>
 <section className="cta section"><div className="cta-orb"/><div className="section-label">06 / PRÓXIMO PROJETO</div><h2>E se o próximo<br/><span>fosse o seu?</span></h2><p>Conte o que você gostaria de melhorar. A gente encontra o caminho digital.</p><a className="button primary large" href={whatsapp}>Conversar com a Karen <ArrowUpRight size={19}/></a><div className="cta-sign">KAREN <span>/ ASSESSORA SEEVEN</span></div></section>
 </main><footer><div className="brand"><span className="brand-mark">V</span><span>SEEVEN<span className="muted">/PROJECTS</span></span></div><span>© {new Date().getFullYear()} Seeven Projects</span><a href="https://www.instagram.com/see_7_ven/" target="_blank" rel="noreferrer"><Instagram size={16}/> @see_7_ven</a></footer><ReelModal item={selected} onClose={()=>setSelected(null)}/><ProjectModal item={selectedProject} onClose={()=>setSelectedProject(null)}/></div>
}

export default App;
