import React,{useEffect,useMemo,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,Menu,X,Play,ChevronRight,ExternalLink,PlayCircle,Filter,Command,MousePointer2,Copy,Check,Plus,Minus,Move3d,Sparkles} from 'lucide-react';
import './styles.css';
import {supabase} from './supabase';
import {seedClients,seedServices,seedContents,seedProjects,seedStats} from './data';

const whatsapp='https://wa.me/5511971493985?text=Ol%C3%A1%2C%20Karen!%20Conheci%20a%20Seeven%20e%20quero%20conversar%20sobre%20um%20projeto.';
const icons={Smartphone:'◈',Globe2:'◌',Utensils:'◇',Target:'⊙',Palette:'✦',Play:'▶',Sparkles:'✧'};
const embedUrl=url=>{const m=url?.match(/instagram\.com\/(?:reel|p)\/([^/?]+)/);return m?`https://www.instagram.com/reel/${m[1]}/embed/`:url};
async function loadTable(table,fallback){if(!supabase)return fallback;const {data,error}=await supabase.from(table).select('*').eq('active',true).order('sort_order',{ascending:true});return error||!data?.length?fallback:data}

function Cursor(){const [p,setP]=useState({x:-100,y:-100}),[hover,setHover]=useState(false);useEffect(()=>{const mv=e=>setP({x:e.clientX,y:e.clientY});window.addEventListener('pointermove',mv);const on=()=>setHover(true),off=()=>setHover(false);const els=document.querySelectorAll('a,button,[data-hover]');els.forEach(e=>{e.addEventListener('pointerenter',on);e.addEventListener('pointerleave',off)});return()=>{window.removeEventListener('pointermove',mv);els.forEach(e=>{e.removeEventListener('pointerenter',on);e.removeEventListener('pointerleave',off)})}},[]);return <div className={'cursor '+(hover?'hover':'')} style={{transform:`translate3d(${p.x}px,${p.y}px,0)`}}/>}
function ReelModal({item,onClose}){if(!item)return null;return <div className="media-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="reel-modal-box"><button className="modal-close" onClick={onClose}><X/></button><iframe src={embedUrl(item.url)} title={item.title} loading="lazy" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"/></div></div>}
function ProjectModal({item,onClose}){if(!item)return null;return <div className="media-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="project-modal-box"><button className="modal-close" onClick={onClose}><X/></button><div className="project-modal-image">{item.cover_url?<img src={item.cover_url} alt=""/>:<div className="project-fallback">{item.title}</div>}</div><div className="project-modal-copy"><span>{item.category}</span><h3>{item.title}</h3><p>{item.description}</p><a className="button primary" href={item.url} target="_blank" rel="noreferrer">Abrir projeto <ExternalLink size={16}/></a></div></div></div>}
function CommandPalette({open,onClose,go,openReel}){if(!open)return null;const actions=[['1','Ver trabalhos',()=>go('showcase')],['2','Explorar portfólio',()=>go('portfolio')],['3','Soluções',()=>go('services')],['4','Abrir case',()=>go('case')],['5','Falar com Karen',()=>location.href=whatsapp]];return <div className="command-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="command-box"><div className="command-top"><Command size={17}/><span>SEE​VEN COMMAND</span><kbd>ESC</kbd></div>{actions.map(([n,label,fn])=><button key={n} onClick={()=>{fn();onClose()}}><b>{n}</b><span>{label}</span><ArrowUpRight size={14}/></button>)}<div className="command-foot">Use <kbd>⌘ K</kbd> ou <kbd>CTRL K</kbd> a qualquer momento</div></div></div>}

function App(){
 const [menu,setMenu]=useState(false),[scroll,setScroll]=useState(0),[clients,setClients]=useState(seedClients),[services,setServices]=useState(seedServices),[contents,setContents]=useState(seedContents),[projects,setProjects]=useState(seedProjects),[filter,setFilter]=useState('TODOS'),[selected,setSelected]=useState(null),[selectedProject,setSelectedProject]=useState(null),[activeService,setActiveService]=useState(0),[activeProject,setActiveProject]=useState(0),[showAll,setShowAll]=useState(false),[palette,setPalette]=useState(false),[copied,setCopied]=useState(false),[tilt,setTilt]=useState({x:0,y:0});
 useEffect(()=>{const f=()=>setScroll(window.scrollY);window.addEventListener('scroll',f,{passive:true});const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if(e.key==='Escape'){setPalette(false);setSelected(null);setSelectedProject(null)}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('scroll',f);window.removeEventListener('keydown',key)}},[]);
 useEffect(()=>{(async()=>{setClients(await loadTable('clients',seedClients));setServices(await loadTable('services',seedServices));setContents(await loadTable('contents',seedContents));setProjects(await loadTable('projects',seedProjects));})()},[]);
 const names=useMemo(()=>['TODOS',...clients.map(c=>c.name)],[clients]);const filtered=filter==='TODOS'?contents:contents.filter(c=>c.client_name===filter);const featured=filtered.filter(c=>c.featured);const visible=showAll?filtered:(featured.length?featured:filtered).slice(0,6);const active=services[activeService]||services[0];const featuredProjects=projects.filter(p=>p.featured).slice(0,3);const focusProject=featuredProjects[activeProject]||featuredProjects[0];
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const copyLink=async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};
 const tiltMove=e=>{const r=e.currentTarget.getBoundingClientRect();setTilt({x:((e.clientX-r.left)/r.width-.5)*10,y:((e.clientY-r.top)/r.height-.5)*-10})};
 return <div className="app"><Cursor/><div className="noise"/>
 <header className={scroll>30?'header scrolled':'header'}><a className="brand" href="#top"><span className="brand-mark">V</span><span>SEE​VEN <i>/PROJECTS</i></span></a><nav className={menu?'nav open':'nav'}><button onClick={()=>go('showcase')}>Trabalhos</button><button onClick={()=>go('services')}>Soluções</button><button onClick={()=>go('portfolio')}>Portfólio</button><button onClick={()=>setPalette(true)} className="cmd-nav"><Command size={13}/> Explore</button><a className="nav-cta" href={whatsapp}>Falar com Karen <ArrowUpRight size={14}/></a></nav><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="top">
 <section className="hero"><div className="hero-grid"/><div className="hero-copy-wrap"><div className="eyebrow"><span className="dot"/> CREATIVE DIGITAL STUDIO <span className="live">●</span></div><h1>Sua marca<br/>merece <em>impacto.</em></h1><p>Design, conteúdo, estratégia e tecnologia para transformar negócios em experiências digitais que não passam despercebidas.</p><div className="hero-actions"><button className="button primary" onClick={()=>go('showcase')}>Explorar trabalho <ArrowDownRight size={17}/></button><a className="text-link" href={whatsapp}>Falar com Karen <ArrowUpRight size={15}/></a></div><div className="hero-micro"><span>SCROLL TO EXPLORE</span><span>01 — 07</span></div></div><div className="hero-product" onMouseMove={tiltMove} onMouseLeave={()=>setTilt({x:0,y:0})} style={{transform:`perspective(1200px) rotateX(${tilt.y}deg) rotateY(${tilt.x}deg)`}}><div className="product-glow"/><div className="product-orbit orbit-a"/><div className="product-orbit orbit-b"/><div className="dashboard"><div className="dash-top"><b>SEE​VEN</b><span>PROJECT OS</span><i>•••</i></div><div className="dash-hero"><small>CREATIVE / DIGITAL / MOTION</small><strong>Make people<br/><em>stop scrolling.</em></strong><button>VIEW WORK <ArrowUpRight size={12}/></button></div><div className="dash-grid"><div><span>PROJECTS</span><b>26</b></div><div><span>DISCIPLINES</span><b>07</b></div><div><span>CASES</span><b>08</b></div></div><div className="dash-bottom"><span>LIVE PORTFOLIO</span><div className="mini-bars"><i/><i/><i/><i/><i/></div></div></div><div className="float-chip chip-a">✦ MOTION <b>07</b></div><div className="float-chip chip-b">DIGITAL <b>∞</b></div></div><div className="hero-side"><span>01</span><span>07</span><i/></div></section>

 <section className="manifesto section"><div className="section-label">01 / POINT OF VIEW</div><div className="manifesto-main"><h2>Não é sobre<br/><span>estar online.</span></h2><p>É sobre criar algo que faz alguém <strong>parar.</strong> Olhar. Sentir. E pensar:</p><div className="quote">“eu quero isso para a minha marca.”</div></div><div className="manifesto-meta"><span>DESIGN × STRATEGY × TECHNOLOGY</span><span>SEE​VEN / 2026</span></div></section>

 <section id="showcase" className="showcase section"><div className="section-label">02 / SELECTED WORK</div><div className="section-intro"><h2>Feito para<br/><span>ser visto.</span></h2><p>Conteúdo não precisa parecer conteúdo. Cada peça é pensada para carregar a identidade, o contexto e a intenção da marca.</p></div><div className="work-feature"><div className="feature-copy"><span>SELECTED / 01</span><h3>{visible[0]?.client_name||'SEE​VEN'}</h3><p>{visible[0]?.title||'Conteúdo que move uma marca.'}</p><button onClick={()=>visible[0]&&setSelected(visible[0])}>Assistir projeto <Play size={14}/></button></div><div className="feature-reel" onClick={()=>visible[0]&&setSelected(visible[0])}>{visible[0]?.poster_url?<img src={visible[0].poster_url} alt=""/>:<div className="poster-fallback"><b>{visible[0]?.client_name}</b><span>{visible[0]?.title}</span></div>}<div className="feature-reel-overlay"/><div className="big-play"><Play size={20}/></div><span className="reel-stamp">REEL / PLAY</span></div></div><div className="filter-bar"><div className="filter-title"><Filter size={13}/> FILTRAR</div><div className="filter-scroll">{names.map(n=><button key={n} className={filter===n?'active':''} onClick={()=>{setFilter(n);setShowAll(false)}}>{n}</button>)}</div></div><div className="reel-grid-v4">{visible.slice(1).map((item,i)=><button className="reel-card-v4" key={item.id||i} onClick={()=>setSelected(item)}><div className="reel-image">{item.poster_url?<img src={item.poster_url} alt="" loading="lazy"/>:<div className="poster-fallback small"><b>{item.client_name}</b><span>{item.title}</span></div>}<div className="reel-overlay-v4"/><div className="card-play"><Play size={15}/></div><span>{String(i+2).padStart(2,'0')}</span></div><div className="reel-card-copy"><small>{item.client_name}</small><strong>{item.title}</strong><i>VIEW REEL <ArrowUpRight size={12}/></i></div></button>)}</div><button className="outline-button" onClick={()=>setShowAll(!showAll)}>{showAll?<><Minus size={14}/> Mostrar menos</>:<><Plus size={14}/> Explorar todos os 26 trabalhos</>}</button></section>

 <section id="services" className="services-v4 section"><div className="section-label">03 / CAPABILITIES</div><div className="section-intro"><h2>Uma equipe.<br/><span>Várias linguagens.</span></h2><p>Escolha o problema. A gente combina as disciplinas certas para resolver.</p></div><div className="capability-layout"><div className="cap-list">{services.map((s,i)=><button key={s.id||i} className={activeService===i?'cap active':'cap'} onMouseEnter={()=>setActiveService(i)} onClick={()=>setActiveService(i)}><span>{String(i+1).padStart(2,'0')}</span><div><small>{s.tag}</small><strong>{s.title}</strong></div><ChevronRight size={17}/></button>)}</div><div className="cap-stage"><div className="stage-grid"/><div className="stage-number">0{activeService+1}</div><div className="stage-word">{active?.tag}</div><div className="stage-card"><div className="stage-card-top"><span>SEE​VEN / {active?.tag}</span><span>LIVE</span></div><h3>{active?.title}</h3><p>{active?.description}</p><div className="stage-visual"><div className="stage-glow"/><div className="stage-lines"><i/><i/><i/><i/></div><b>{active?.title?.split(' ')[0]?.toUpperCase()}</b></div><button onClick={()=>go('cta')}>Quero isso para minha marca <ArrowUpRight size={14}/></button></div></div></div></section>

 <section id="portfolio" className="portfolio-v4 section"><div className="section-label">04 / PORTFOLIO</div><div className="section-intro"><h2>Projetos com<br/><span>história.</span></h2><p>Do primeiro conceito à entrega final. Abra um projeto e explore o trabalho por trás da imagem.</p></div><div className="project-browser"><div className="project-nav"><span>SELECTED PROJECT</span><div><button onClick={()=>setActiveProject((activeProject-1+featuredProjects.length)%featuredProjects.length)}>←</button><b>0{activeProject+1}</b><button onClick={()=>setActiveProject((activeProject+1)%featuredProjects.length)}>→</button></div></div><button className="project-hero" onClick={()=>setSelectedProject(focusProject)}><div className="project-cover">{focusProject?.cover_url?<img src={focusProject.cover_url} alt=""/>:<div className="project-fallback">{focusProject?.title}</div>}<div className="project-cover-shade"/></div><div className="project-info"><span>{focusProject?.category}</span><h3>{focusProject?.title}</h3><p>{focusProject?.description}</p><div className="project-open">ABRIR CASE <ArrowUpRight size={15}/></div></div></button></div><div className="project-strip">{projects.filter(p=>p!==focusProject).map((p,i)=><button key={p.id} onClick={()=>setSelectedProject(p)}><img src={p.cover_url} alt="" loading="lazy"/><span>0{i+2}</span><strong>{p.title}</strong></button>)}</div><a className="behance-link" href="https://www.behance.net/wedeseeven" target="_blank" rel="noreferrer">Explorar Behance completo <ExternalLink size={14}/></a></section>

 <section id="case" className="case-v4 section"><div className="case-grid-bg"/><div className="section-label">05 / CASE STUDY</div><div className="case-top"><div><span className="case-tag">SINDPETSHOP-SP</span><h2>Comunicação<br/><span>sindical não é fácil.</span></h2></div><div className="case-summary"><p>Quando o assunto é complexo, a comunicação precisa ser ainda mais clara. Construímos uma presença digital capaz de transformar informação em atenção.</p><button onClick={()=>setSelectedProject(projects[1])}>VER PROJETO <ArrowUpRight size={14}/></button></div></div><div className="case-stats">{seedStats.map((s,i)=><div key={s.label}><small>{s.label}</small><strong>{s.value}<em>{s.suffix}</em></strong><span>{s.delta}</span></div>)}</div><div className="case-story"><div className="story-step active"><span>01</span><b>DESAFIO</b><p>Comunicar direitos, campanhas e informação sem perder relevância no feed.</p></div><div className="story-line"/><div className="story-step"><span>02</span><b>DIREÇÃO</b><p>Identidade, conteúdo, motion e campanhas trabalhando como um único sistema.</p></div><div className="story-line"/><div className="story-step"><span>03</span><b>RESULTADO</b><p>Uma presença mais consistente e dados reais para medir a evolução.</p></div></div></section>

 <section className="lab section"><div className="section-label">06 / LAB</div><div className="lab-head"><h2>Nem tudo precisa<br/><span>ser cliente.</span></h2><p>Experimentação também é portfólio. 3D, motion, IA, interfaces e ideias que existem para testar até onde podemos levar uma imagem.</p></div><div className="lab-cards"><div className="lab-card lab-big"><div className="lab-orb"><Move3d size={20}/></div><span>3D / EXPERIMENT</span><strong>Construindo<br/><em>novas dimensões.</em></strong><i>01</i></div><div className="lab-card"><span>MOTION</span><strong>Design<br/>em movimento.</strong><i>02</i></div><div className="lab-card"><span>AI / CONCEPT</span><strong>Ideias antes<br/>do briefing.</strong><i>03</i></div></div></section>

 <section id="cta" className="cta-v4 section"><div className="cta-glow"/><div className="section-label">07 / NEXT PROJECT</div><div className="cta-inner"><span>SEU PRÓXIMO PROJETO</span><h2>Talvez sua marca<br/>seja o <em>próximo.</em></h2><p>Se você chegou até aqui, já viu o que podemos fazer. Agora vamos descobrir o que sua marca precisa.</p><div className="cta-actions"><a className="button primary large" href={whatsapp}>Falar com a Karen <ArrowUpRight size={18}/></a><button className="share-button" onClick={copyLink}>{copied?<><Check size={15}/> Link copiado</>:<><Copy size={15}/> Compartilhar</>}</button></div></div><div className="cta-bottom"><span>SEE​VEN PROJECTS</span><span>SP / BR</span><span>© 2026</span></div></section>
 </main><footer><span>SEE​VEN / PROJECTS</span><span>DESIGN × STRATEGY × TECHNOLOGY</span><a href="https://www.instagram.com/see_7_ven/" target="_blank" rel="noreferrer">INSTAGRAM <ArrowUpRight size={11}/></a></footer>
 <CommandPalette open={palette} onClose={()=>setPalette(false)} go={go}/>{selected&&<ReelModal item={selected} onClose={()=>setSelected(null)}/>} {selectedProject&&<ProjectModal item={selectedProject} onClose={()=>setSelectedProject(null)}/>}</div>
}
export default App;
