import React,{useEffect,useMemo,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,Menu,X,Play,ChevronRight,ExternalLink,Filter,Command,Copy,Check,Plus,Minus,Move3d,Instagram,MessageCircle,Search} from 'lucide-react';
import './styles.css';
import {supabase} from './supabase';
import {seedClients,seedServices,seedContents,seedProjects,seedStats} from './data';

const KAREN='https://wa.me/5511971493985?text=Ol%C3%A1%2C%20Karen!%20Conheci%20a%20Seeven%20e%20quero%20conversar%20sobre%20um%20projeto.';
const GUSTAVO='https://wa.me/5511920626850?text=Ol%C3%A1%2C%20Gustavo!%20Conheci%20a%20Seeven%20e%20quero%20conversar%20sobre%20um%20projeto.';
const embedUrl=url=>{const m=url?.match(/instagram\.com\/(?:reel|p)\/([^/?]+)/);return m?`https://www.instagram.com/reel/${m[1]}/embed/`:url};
async function loadTable(table,fallback){if(!supabase)return fallback;const {data,error}=await supabase.from(table).select('*').eq('active',true).order('sort_order',{ascending:true});return error||!data?.length?fallback:data}

function useScrollExperience(){useEffect(()=>{const els=[...document.querySelectorAll('[data-reveal]')];els.forEach((el,i)=>{el.classList.add('scroll-reveal');el.style.setProperty('--reveal-delay',`${Math.min(i%7,6)*65}ms`)});const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.08,rootMargin:'0px 0px -7% 0px'});els.forEach(el=>io.observe(el));let raf=0;const parallax=()=>{if(raf)return;raf=requestAnimationFrame(()=>{const y=window.scrollY;document.querySelectorAll('[data-parallax]').forEach(el=>el.style.setProperty('--parallax-y',`${y*Number(el.dataset.parallax||.06)}px`));raf=0})};window.addEventListener('scroll',parallax,{passive:true});parallax();return()=>{io.disconnect();window.removeEventListener('scroll',parallax);cancelAnimationFrame(raf)}},[])}
function Cursor(){const [p,setP]=useState({x:-100,y:-100}),[hover,setHover]=useState(false);useEffect(()=>{const mv=e=>setP({x:e.clientX,y:e.clientY});window.addEventListener('pointermove',mv);const on=()=>setHover(true),off=()=>setHover(false);const bind=()=>document.querySelectorAll('a,button,[data-hover]').forEach(e=>{e.addEventListener('pointerenter',on);e.addEventListener('pointerleave',off)});bind();const mo=new MutationObserver(bind);mo.observe(document.body,{subtree:true,childList:true});return()=>{window.removeEventListener('pointermove',mv);mo.disconnect()}},[]);return <div className={'cursor '+(hover?'hover':'')} style={{transform:`translate3d(${p.x}px,${p.y}px,0)`}}/>}
function ReelModal({item,onClose}){if(!item)return null;return <div className="media-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="reel-modal-box"><button className="modal-close" onClick={onClose}><X/></button><iframe src={embedUrl(item.url)} title={item.title} loading="lazy" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"/></div></div>}
function ProjectModal({item,onClose}){if(!item)return null;return <div className="media-modal" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="project-modal-box"><button className="modal-close" onClick={onClose}><X/></button><div className="project-modal-image">{item.cover_url?<img src={item.cover_url} alt=""/>:<div className="project-fallback">{item.title}</div>}</div><div className="project-modal-copy"><span>{item.category}</span><h3>{item.title}</h3><p>{item.description}</p><a className="button primary" href={item.url} target="_blank" rel="noreferrer">Abrir no Behance <ExternalLink size={16}/></a></div></div></div>}
function CommandPalette({open,onClose,go}){if(!open)return null;const actions=[['1','Ver trabalhos',()=>go('work')],['2','Cases',()=>go('cases')],['3','Soluções',()=>go('services')],['4','Portfólio Behance',()=>go('portfolio')],['5','Falar com Karen',()=>location.href=KAREN],['6','Falar com Gustavo',()=>location.href=GUSTAVO]];return <div className="command-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="command-box"><div className="command-top"><Command size={16}/><span>SEE7VEN / COMMAND</span><kbd>ESC</kbd></div>{actions.map(([n,label,fn])=><button key={n} onClick={()=>{fn();onClose()}}><b>{n}</b><span>{label}</span><ArrowUpRight size={14}/></button>)}<div className="command-foot">Use <kbd>⌘ K</kbd> ou <kbd>CTRL K</kbd> para navegar</div></div></div>}

function App(){
 const [menu,setMenu]=useState(false),[scroll,setScroll]=useState(0),[clients,setClients]=useState(seedClients),[services,setServices]=useState(seedServices),[contents,setContents]=useState(seedContents),[projects,setProjects]=useState(seedProjects),[filter,setFilter]=useState('TODOS'),[category,setCategory]=useState('TODOS'),[selected,setSelected]=useState(null),[selectedProject,setSelectedProject]=useState(null),[activeService,setActiveService]=useState(0),[showAll,setShowAll]=useState(false),[palette,setPalette]=useState(false),[copied,setCopied]=useState(false),[query,setQuery]=useState('');
 useScrollExperience();
 useEffect(()=>{const f=()=>setScroll(window.scrollY);window.addEventListener('scroll',f,{passive:true});const key=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(v=>!v)}if(e.key==='Escape'){setPalette(false);setSelected(null);setSelectedProject(null)}};window.addEventListener('keydown',key);return()=>{window.removeEventListener('scroll',f);window.removeEventListener('keydown',key)}},[]);
 useEffect(()=>{(async()=>{setClients(await loadTable('clients',seedClients));setServices(await loadTable('services',seedServices));setContents(await loadTable('contents',seedContents));setProjects(await loadTable('projects',seedProjects));})()},[]);
 const names=useMemo(()=>['TODOS',...clients.map(c=>c.name)],[clients]);
 const cats=useMemo(()=>['TODOS',...new Set(contents.map(c=>c.category).filter(Boolean))],[contents]);
 const filtered=useMemo(()=>contents.filter(c=>(filter==='TODOS'||c.client_name===filter)&&(category==='TODOS'||c.category===category)&&(`${c.client_name} ${c.title} ${c.category}`.toLowerCase().includes(query.toLowerCase()))),[contents,filter,category,query]);
 const featured=filtered.filter(c=>c.featured); const workItems=showAll?filtered:(featured.length?featured:filtered).slice(0,8); const heroWork=workItems[0]||contents[0];
 const go=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 const copyLink=async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{}};
 return <div className="app"><Cursor/><div className="scroll-progress" style={{width:`${Math.min(100,(scroll/(document.documentElement.scrollHeight-window.innerHeight||1))*100)}%`}}/><div className="noise"/>
 <header className={scroll>40?'header scrolled':'header'}><a className="brand" href="#top"><span className="brand-mark">V</span><span>SEE7VEN <i>/ PROJECTS</i></span></a><nav className={menu?'nav open':'nav'}><button onClick={()=>go('work')}>Trabalhos</button><button onClick={()=>go('services')}>Soluções</button><button onClick={()=>go('portfolio')}>Portfólio</button><button className="cmd-nav" onClick={()=>setPalette(true)}><Command size={13}/> Explorar</button><a className="nav-cta" href={KAREN}>Falar com Karen <ArrowUpRight size={14}/></a></nav><button className="menu-btn" onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="top">
 <section className="hero-v5"><div className="hero-noise-grid"/><div className="hero-v5-copy" data-reveal><div className="eyebrow"><span className="dot"/> CREATIVE DIGITAL STUDIO <span className="live">LIVE / 2026</span></div><h1>Fazemos marcas<br/><em>pararem.</em></h1><p>Design, conteúdo, estratégia e tecnologia. Uma operação criativa para transformar presença digital em percepção.</p><div className="hero-actions"><button className="button primary" onClick={()=>go('work')}>Ver o trabalho <ArrowDownRight size={17}/></button><a className="text-link" href={KAREN}>Começar uma conversa <ArrowUpRight size={15}/></a></div></div>
 <div className="hero-workcard" data-reveal onClick={()=>heroWork&&setSelected(heroWork)}><div className="hero-card-meta"><span>SELECTED WORK / 001</span><span>{heroWork?.category||'MOTION'}</span></div><div className="hero-card-media">{heroWork?.poster_url?<img src={heroWork.poster_url} alt=""/>:<div className="poster-fallback cinematic"><span>{heroWork?.client_name}</span><b>{heroWork?.title}</b></div>}<div className="media-scan"/><div className="play-circle"><Play size={17}/></div><span className="media-index">REEL 01 / 32</span></div><div className="hero-card-foot"><div><small>{heroWork?.client_name}</small><strong>{heroWork?.title}</strong></div><ArrowUpRight size={18}/></div></div>
 <div className="hero-stats"><div><b>32</b><span>REELS</span></div><div><b>11</b><span>MARCAS</span></div><div><b>08</b><span>CASES</span></div><div><b>07</b><span>DISCIPLINAS</span></div></div><div className="hero-scroll">SCROLL / EXPLORE <span>↓</span></div></section>

 <section className="ticker"><div>DESIGN</div><i>✦</i><div>STRATEGY</div><i>✦</i><div>MOTION</div><i>✦</i><div>WEB</div><i>✦</i><div>CONTENT</div><i>✦</i><div>PERFORMANCE</div><i>✦</i><div>BRANDING</div><i>✦</i></section>

 <section className="statement section" data-reveal><div className="section-label">01 / POV</div><div className="statement-layout"><h2>Não queremos<br/>ser mais uma<br/><span>agência.</span></h2><div><p>Queremos que o seu negócio pareça <strong>maior, mais claro e mais desejável</strong> no primeiro contato.</p><p className="muted">O site é só uma das ferramentas. A experiência inteira é o produto.</p></div></div></section>

 <section id="work" className="work-v5 section"><div className="section-label">02 / SELECTED WORK</div><div className="work-heading" data-reveal><div><span>O portfólio é a prova.</span><h2>Olhe primeiro.<br/><em>Leia depois.</em></h2></div><p>Uma seleção do que produzimos para marcas, eventos, negócios locais e projetos digitais.</p></div>
 <div className="work-controls" data-reveal><div className="control-row"><div className="control-label"><Filter size={13}/> CLIENTES</div><div className="chips">{names.map(n=><button key={n} className={filter===n?'active':''} onClick={()=>{setFilter(n);setShowAll(false)}}>{n}</button>)}</div></div><div className="control-row"><div className="control-label">TIPO</div><div className="chips">{cats.map(c=><button key={c} className={category===c?'active':''} onClick={()=>{setCategory(c);setShowAll(true)}}>{c}</button>)}</div></div><div className="search-box"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar trabalho..."/></div></div>
 <div className="editorial-grid" data-reveal>{workItems.slice(0,5).map((item,i)=><button key={item.id||i} className={'editorial-card card-'+i} onClick={()=>setSelected(item)}><div className="editorial-media">{item.poster_url?<img src={item.poster_url} alt="" loading="lazy"/>:<div className="poster-fallback"><span>{item.client_name}</span><b>{item.title}</b></div>}<div className="editorial-overlay"/><span className="number">{String(i+1).padStart(2,'0')}</span><span className="open-mark"><Play size={15}/></span></div><div className="editorial-copy"><div><small>{item.client_name}</small><strong>{item.title}</strong></div><span>{item.category}</span></div></button>)}</div>
 <div className="archive-head"><span>{filtered.length} trabalhos encontrados</span><button onClick={()=>setShowAll(v=>!v)}>{showAll?<><Minus size={13}/> Fechar arquivo</>:<><Plus size={13}/> Abrir arquivo completo</>}</button></div>
 {showAll&&<div className="archive-grid" data-reveal>{filtered.map((item,i)=><button key={item.id||i} onClick={()=>setSelected(item)}><div className="archive-thumb">{item.poster_url?<img src={item.poster_url} alt="" loading="lazy"/>:<div className="poster-fallback"><span>{item.client_name}</span></div>}<span>{String(i+1).padStart(2,'0')}</span></div><div><small>{item.client_name}</small><strong>{item.title}</strong><em>{item.category}</em></div><ArrowUpRight size={15}/></button>)}</div>}
 </section>

 <section id="services" className="services-v5 section"><div className="section-label">03 / DISCIPLINES</div><div className="services-head" data-reveal><h2>O problema muda.<br/><em>A linguagem também.</em></h2><p>Não vendemos pacotes. Montamos a combinação de disciplinas que o projeto pede.</p></div><div className="services-layout"><div className="service-list" data-reveal>{services.map((s,i)=><button key={s.id||i} className={activeService===i?'active':''} onMouseEnter={()=>setActiveService(i)} onClick={()=>setActiveService(i)}><span>0{i+1}</span><div><small>{s.tag}</small><strong>{s.title}</strong></div><ChevronRight size={17}/></button>)}</div><div className="service-stage" data-reveal><div className="stage-grid"/><span className="stage-index">0{activeService+1}</span><span className="stage-tag">{services[activeService]?.tag}</span><div className="stage-copy"><h3>{services[activeService]?.title}</h3><p>{services[activeService]?.description}</p><button onClick={()=>go('contact')}>Quero conversar <ArrowUpRight size={14}/></button></div><div className="stage-art"><div/><div/><div/></div></div></div></section>

 <section id="portfolio" className="portfolio-v5 section"><div className="section-label">04 / PROJECTS</div><div className="portfolio-head" data-reveal><div><span>BEHANCE / SELECTED</span><h2>Projeto não é<br/><em>só imagem.</em></h2></div><p>Identidade, campanha, 3D, eventos e direção visual. Explore alguns projetos com mais contexto.</p></div><div className="project-wall" data-reveal>{projects.map((p,i)=><button key={p.id} className={i===0?'project-tile featured':''} onClick={()=>setSelectedProject(p)}><img src={p.cover_url} alt="" loading="lazy"/><div className="project-shade"/><span>0{i+1}</span><div><small>{p.category}</small><strong>{p.title}</strong></div></button>)}</div><a className="behance-link" href="https://www.behance.net/wedeseeven" target="_blank" rel="noreferrer">Abrir portfólio completo no Behance <ExternalLink size={14}/></a></section>

 <section id="cases" className="case-v5 section"><div className="section-label">05 / CASE STUDY</div><div className="case-hero" data-reveal><div className="case-copy"><span>SINDPETSHOP-SP / AGOSTO 2026</span><h2>Comunicação<br/><em>sindical não é fácil.</em></h2><p>Transformamos uma pauta complexa em uma presença digital mais clara, consistente e capaz de gerar atenção.</p><button onClick={()=>setSelectedProject(projects[1])}>Explorar case <ArrowUpRight size={15}/></button></div><div className="case-visual"><div className="case-poster">SIND<br/><em>PET</em></div><span>CASE / 01</span></div></div><div className="case-metrics" data-reveal>{seedStats.map(s=><div key={s.label}><small>{s.label}</small><b>{s.value}<em>{s.suffix}</em></b><span>{s.delta}</span></div>)}</div><div className="case-story" data-reveal><div><span>01</span><small>DESAFIO</small><p>Comunicar direitos, campanhas e informação sem desaparecer no feed.</p></div><div><span>02</span><small>DIREÇÃO</small><p>Conteúdo, identidade, motion e calendário trabalhando como um único sistema.</p></div><div><span>03</span><small>EVOLUÇÃO</small><p>Mais consistência visual e dados reais para acompanhar a evolução do perfil.</p></div></div></section>

 <section className="lab-v5 section"><div className="section-label">06 / LAB</div><div className="lab-head" data-reveal><h2>Também criamos<br/><em>o que ainda não existe.</em></h2><p>Experimentação, 3D, motion e interfaces. Porque repertório também se constrói fora do briefing.</p></div><div className="lab-grid" data-reveal><div className="lab-card big"><span>03D / EXPERIMENT</span><Move3d/><strong>Ideias que<br/><em>ganham volume.</em></strong><i>01</i></div><div className="lab-card"><span>MOTION</span><strong>Design<br/>em movimento.</strong><i>02</i></div><div className="lab-card"><span>DIGITAL</span><strong>Interfaces<br/>com intenção.</strong><i>03</i></div></div></section>

 <section id="contact" className="contact-v5 section"><div className="contact-orb" data-parallax="-0.05"/><div className="section-label">07 / NEXT PROJECT</div><div className="contact-inner" data-reveal><span>SEU PROJETO PODE SER O PRÓXIMO.</span><h2>Vamos fazer<br/><em>algo impossível</em><br/>de ignorar.</h2><p>Você traz o problema. A gente encontra a forma, a linguagem e a experiência.</p><div className="contact-actions"><a className="contact-card primary" href={KAREN}><MessageCircle/><div><small>FALAR COM</small><strong>KAREN</strong></div><ArrowUpRight/></a><a className="contact-card" href={GUSTAVO}><MessageCircle/><div><small>FALAR COM</small><strong>GUSTAVO</strong></div><ArrowUpRight/></a></div><div className="contact-tools"><button onClick={copyLink}>{copied?<><Check size={14}/> Link copiado</>:<><Copy size={14}/> Compartilhar portfólio</>}</button><a href="https://www.instagram.com/see_7_ven/" target="_blank" rel="noreferrer"><Instagram size={14}/> Instagram</a></div></div><div className="contact-bottom"><span>SEE7VEN PROJECTS</span><span>SÃO PAULO / BR</span><span>© 2026</span></div></section>
 </main><footer><span>SEE7VEN / PROJECTS</span><span>DESIGN × STRATEGY × TECHNOLOGY</span><a href="https://www.instagram.com/see_7_ven/" target="_blank" rel="noreferrer">INSTAGRAM <ArrowUpRight size={11}/></a></footer>
 <CommandPalette open={palette} onClose={()=>setPalette(false)} go={go}/>{selected&&<ReelModal item={selected} onClose={()=>setSelected(null)}/>} {selectedProject&&<ProjectModal item={selectedProject} onClose={()=>setSelectedProject(null)}/>}</div>
}
export default App;
